import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

public class LiftLoop extends javax.swing.JFrame {
    char click = 'n';
    public LiftLoop() {
        initComponents();
        new library().execute();
        new home().execute();
        setSize(1174,738);  
        setLocationRelativeTo(null);
        setResizable(false);
        
        L_Password.setEchoChar((char)0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        adminIcon = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        L_Username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        L_Password = new javax.swing.JPasswordField();
        L_ShowPassword = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        forgotPassword = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        signUp = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        S_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        S_Username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        S_Password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        S_RetypePassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        S_Female = new javax.swing.JRadioButton();
        S_male = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        S_SecQues = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        S_SecAns = new javax.swing.JTextField();
        S_Submit = new javax.swing.JButton();
        S_Back = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        S_FillPassword = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        offer_from = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        offer_to = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        offer_date = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        offer_time = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        offer_seats = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        offer_amount = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        seak_from = new javax.swing.JLabel();
        booking_from = new javax.swing.JTextField();
        seak_to = new javax.swing.JLabel();
        booking_to = new javax.swing.JTextField();
        seak_date = new javax.swing.JLabel();
        booking_date = new javax.swing.JTextField();
        seak_time = new javax.swing.JLabel();
        booking_time = new javax.swing.JTextField();
        seak_pass = new javax.swing.JLabel();
        booking_passenger = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        details = new javax.swing.JTextArea();
        book = new javax.swing.JButton();
        homeImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1170, 260);

        adminButton.setBackground(new java.awt.Color(0, 153, 153));
        adminButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setText("Login");
        adminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminButtonMouseClicked(evt);
            }
        });
        jPanel1.add(adminButton);
        adminButton.setBounds(490, 540, 170, 60);

        adminIcon.setFont(new java.awt.Font("Illuma Black", 2, 36)); // NOI18N
        adminIcon.setForeground(new java.awt.Color(0, 153, 153));
        adminIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminIcon.setText("LiftLoop");
        jPanel1.add(adminIcon);
        adminIcon.setBounds(400, 330, 380, 100);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CARPOOLING APP");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(420, 400, 350, 70);

        getContentPane().add(jPanel1, "card2");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        L_Username.setText("Enter Username");
        L_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                L_UsernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                L_UsernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                L_UsernameKeyTyped(evt);
            }
        });
        jPanel3.add(L_Username);
        L_Username.setBounds(120, 130, 370, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Login");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(250, 40, 140, 50);

        L_Password.setText("Enter Password");
        L_Password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        L_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                L_PasswordKeyTyped(evt);
            }
        });
        jPanel3.add(L_Password);
        L_Password.setBounds(120, 240, 370, 60);

        L_ShowPassword.setText("Show Password");
        L_ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_ShowPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(L_ShowPassword);
        L_ShowPassword.setBounds(120, 340, 230, 40);

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Login");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(230, 410, 190, 50);

        jLabel5.setText("Forgot");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(280, 510, 50, 30);

        forgotPassword.setForeground(new java.awt.Color(0, 153, 153));
        forgotPassword.setText("Password?");
        jPanel3.add(forgotPassword);
        forgotPassword.setBounds(320, 510, 90, 30);

        jLabel7.setText("Don't have an account?");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(220, 570, 170, 20);

        signUp.setForeground(new java.awt.Color(0, 153, 153));
        signUp.setText("Sign Up");
        signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpMouseClicked(evt);
            }
        });
        jPanel3.add(signUp);
        signUp.setBounds(350, 570, 60, 20);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(10, 10, 65, 29);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(240, 20, 640, 630);

        getContentPane().add(jPanel2, "card3");

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel2.setText("Name");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(20, 90, 50, 30);

        S_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_NameActionPerformed(evt);
            }
        });
        jPanel5.add(S_Name);
        S_Name.setBounds(200, 90, 240, 30);

        jLabel3.setText("Username");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(20, 140, 80, 30);

        S_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_UsernameActionPerformed(evt);
            }
        });
        jPanel5.add(S_Username);
        S_Username.setBounds(200, 140, 240, 30);

        jLabel6.setText("Password");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(20, 190, 70, 30);

        S_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_PasswordActionPerformed(evt);
            }
        });
        jPanel5.add(S_Password);
        S_Password.setBounds(200, 190, 240, 30);

        jLabel8.setText("Retype Password");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(20, 240, 130, 30);

        S_RetypePassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                S_RetypePasswordKeyReleased(evt);
            }
        });
        jPanel5.add(S_RetypePassword);
        S_RetypePassword.setBounds(200, 240, 240, 30);

        jLabel10.setText("Gender");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(30, 300, 51, 20);

        S_Female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(S_Female);
        S_Female.setForeground(new java.awt.Color(51, 51, 51));
        S_Female.setText("Female");
        jPanel5.add(S_Female);
        S_Female.setBounds(200, 300, 83, 29);

        S_male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(S_male);
        S_male.setForeground(new java.awt.Color(51, 51, 51));
        S_male.setText("Male");
        S_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_maleActionPerformed(evt);
            }
        });
        jPanel5.add(S_male);
        S_male.setBounds(330, 300, 80, 29);

        jLabel12.setText("Security Question");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(20, 350, 140, 30);

        S_SecQues.setForeground(new java.awt.Color(51, 51, 51));
        S_SecQues.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your nick name?", "What is your favourite colour?", "What is your bestfriend name?", "What is name of your favourite teacher?", "What is your favourite subject?", "What is your favourite sport?", "What is your hobby?", "What is your favourite food?", "Who is your idol?", "How many friend you have?" }));
        jPanel5.add(S_SecQues);
        S_SecQues.setBounds(200, 350, 240, 26);

        jLabel13.setText("Security Answer");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(20, 410, 120, 30);
        jPanel5.add(S_SecAns);
        S_SecAns.setBounds(200, 400, 240, 30);

        S_Submit.setBackground(new java.awt.Color(0, 153, 153));
        S_Submit.setForeground(new java.awt.Color(255, 255, 255));
        S_Submit.setText("Submit");
        S_Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_SubmitMouseClicked(evt);
            }
        });
        S_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_SubmitActionPerformed(evt);
            }
        });
        jPanel5.add(S_Submit);
        S_Submit.setBounds(60, 470, 83, 40);

        S_Back.setBackground(new java.awt.Color(0, 153, 153));
        S_Back.setForeground(new java.awt.Color(255, 255, 255));
        S_Back.setText("Back");
        S_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_BackMouseClicked(evt);
            }
        });
        jPanel5.add(S_Back);
        S_Back.setBounds(300, 470, 90, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Sign Up");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(240, 10, 110, 40);

        S_FillPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                S_FillPasswordKeyReleased(evt);
            }
        });
        jPanel5.add(S_FillPassword);
        S_FillPassword.setBounds(460, 240, 220, 30);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(290, 50, 570, 600);

        getContentPane().add(jPanel4, "card4");

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Become a LiftLoop Driver and save on travel costs");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(120, 30, 810, 60);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("by sharing your ride with passengers");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(120, 100, 790, 60);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel16.setText("From");
        jPanel7.add(jLabel16);
        jLabel16.setBounds(50, 50, 80, 20);

        offer_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offer_fromActionPerformed(evt);
            }
        });
        jPanel7.add(offer_from);
        offer_from.setBounds(300, 50, 230, 26);

        jLabel17.setText("To");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(50, 100, 19, 20);
        jPanel7.add(offer_to);
        offer_to.setBounds(300, 100, 230, 26);

        jLabel18.setText("Date");
        jPanel7.add(jLabel18);
        jLabel18.setBounds(50, 150, 32, 20);
        jPanel7.add(offer_date);
        offer_date.setBounds(300, 150, 230, 26);

        jLabel19.setText("Time");
        jPanel7.add(jLabel19);
        jLabel19.setBounds(50, 200, 36, 20);
        jPanel7.add(offer_time);
        offer_time.setBounds(300, 200, 230, 26);

        jLabel20.setText("Avaliable Seats");
        jPanel7.add(jLabel20);
        jLabel20.setBounds(50, 250, 110, 20);

        offer_seats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offer_seatsActionPerformed(evt);
            }
        });
        jPanel7.add(offer_seats);
        offer_seats.setBounds(300, 250, 230, 26);

        jLabel21.setText("Amount");
        jPanel7.add(jLabel21);
        jLabel21.setBounds(50, 300, 57, 20);
        jPanel7.add(offer_amount);
        offer_amount.setBounds(300, 300, 230, 26);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Offer A Ride");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);
        jButton2.setBounds(260, 380, 130, 29);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(230, 200, 620, 450);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setForeground(new java.awt.Color(0, 153, 153));
        jButton6.setText("Back");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel6.add(jButton6);
        jButton6.setBounds(1010, 50, 65, 29);

        getContentPane().add(jPanel6, "card5");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        seak_from.setText("From");
        jPanel8.add(seak_from);
        seak_from.setBounds(60, 270, 100, 40);
        jPanel8.add(booking_from);
        booking_from.setBounds(170, 280, 270, 26);

        seak_to.setText("To");
        jPanel8.add(seak_to);
        seak_to.setBounds(580, 280, 40, 20);
        jPanel8.add(booking_to);
        booking_to.setBounds(680, 280, 270, 26);

        seak_date.setText("Date");
        jPanel8.add(seak_date);
        seak_date.setBounds(60, 330, 32, 20);
        jPanel8.add(booking_date);
        booking_date.setBounds(170, 330, 270, 26);

        seak_time.setText("Time");
        jPanel8.add(seak_time);
        seak_time.setBounds(580, 330, 36, 20);

        booking_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booking_timeActionPerformed(evt);
            }
        });
        jPanel8.add(booking_time);
        booking_time.setBounds(680, 330, 270, 26);

        seak_pass.setText("Passengers");
        jPanel8.add(seak_pass);
        seak_pass.setBounds(60, 380, 80, 20);
        jPanel8.add(booking_passenger);
        booking_passenger.setBounds(170, 380, 270, 26);

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Search");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4);
        jButton4.setBounds(870, 380, 79, 29);

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Publish Ride");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel8.add(jButton5);
        jButton5.setBounds(990, 20, 120, 40);

        details.setColumns(20);
        details.setRows(5);
        jScrollPane1.setViewportView(details);

        jPanel8.add(jScrollPane1);
        jScrollPane1.setBounds(100, 440, 960, 170);

        book.setBackground(new java.awt.Color(0, 153, 153));
        book.setForeground(new java.awt.Color(255, 255, 255));
        book.setText("Book");
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookMouseClicked(evt);
            }
        });
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jPanel8.add(book);
        book.setBounds(560, 630, 67, 29);
        jPanel8.add(homeImage);
        homeImage.setBounds(0, 0, 1180, 250);

        getContentPane().add(jPanel8, "card6");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButtonMouseClicked
        // TODO add your handling code here:
        click = 'a';
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);  
    }//GEN-LAST:event_adminButtonMouseClicked

    private void L_UsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_L_UsernameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_L_UsernameKeyReleased

    private void S_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_NameActionPerformed

    private void signUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpMouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel4.setVisible(true);
    }//GEN-LAST:event_signUpMouseClicked

    private void S_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_BackMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanel2.setVisible(true);
        
    }//GEN-LAST:event_S_BackMouseClicked

    private void S_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_PasswordActionPerformed

    private void S_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_UsernameActionPerformed

    private void S_SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_SubmitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_S_SubmitMouseClicked

    private void L_ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_ShowPasswordActionPerformed
        // TODO add your handling code here:
        if(L_ShowPassword.isSelected()){
            L_Password.setEchoChar((char)0);
        }
        else{
            L_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_L_ShowPasswordActionPerformed

    private void S_FillPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_S_FillPasswordKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_S_FillPasswordKeyReleased

    private void S_RetypePasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_S_RetypePasswordKeyReleased
        // TODO add your handling code here:
        String s1 = S_Password.getText();
        String s2 = S_RetypePassword.getText();
        
        if(s1.equals("")){
            S_FillPassword.setText("Please Fill Password");
        }
        else{
            if(s2.length() <= s1.length()){
                for(int i = 0;i<s2.length();i++){
                    if(s2.charAt(i) != s1.charAt(i)){
                        S_FillPassword.setText("Password Not Matched");
                        break;
                    }
                    else{
                        S_FillPassword.setText(null);
                    }
                }
            }
            else{
                S_FillPassword.setText("Password Not Matched");
            }
        }
    }//GEN-LAST:event_S_RetypePasswordKeyReleased

    private void L_UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_L_UsernameKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_L_UsernameKeyPressed

    private void L_UsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_L_UsernameKeyTyped
        // TODO add your handling code here:
        String s = L_Username.getText();
        
        if(s.equals("Enter Username")){
            L_Username.setText(null);
        }
        else if(s.equals("")){
            L_Username.setText("Enter Username");
        }
    }//GEN-LAST:event_L_UsernameKeyTyped

    private void L_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_L_PasswordKeyTyped
        // TODO add your handling code here:
        String s = L_Password.getText();
        
        if(s.equals("Enter Password")){
            L_Password.setText(null);
            L_Password.setEchoChar('*');
        }
        else if(s.equals("")){
            L_Password.setText("Enter Password");
            L_Password.setEchoChar((char)0);
        }
    }//GEN-LAST:event_L_PasswordKeyTyped

    private void S_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_SubmitActionPerformed
        // TODO add your handling code here:
        if(click == 'a'){
            try{
                String name = S_Name.getText();
                String username = S_Username.getText();
                String password = S_Password.getText();
                String gender = "";
                if(S_Female.isSelected()){
                    gender = "Female";
                }
                else if(S_male.isSelected()){
                    gender = "Male";
                }
                String secQues = S_SecQues.getSelectedItem().toString();
//                String image = S_UploadPhoto.getSelectedItem().toString();
                String secAns = S_SecAns.getText();


                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carpooling","root","root");
                Statement stmt = con.createStatement();
                stmt.executeUpdate("insert into users(name,username,password,gender,securityQues,SecurityAns) values('"+name+"','"+username+"','"+password+"','"+gender+"','"+secQues+"','"+secAns+"')");
                JOptionPane.showMessageDialog(null,"Data Inserted");
                jPanel4.setVisible(false);
                jPanel6.setVisible(true);
            }
            catch(Exception ee){
                System.out.println(ee);
            }
        }
    }//GEN-LAST:event_S_SubmitActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
        jPanel2.setVisible(false);
        jPanel8.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void S_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_maleActionPerformed

    private void offer_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offer_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offer_fromActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void booking_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booking_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booking_timeActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
      
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        jPanel8.setVisible(false);
        jPanel6.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String from = offer_from.getText();
            String to = offer_to.getText();
            String date = offer_date.getText();
            String time = offer_time.getText();
            String seats = offer_seats.getText();
            String amount = offer_amount.getText();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carpooling","root","root");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("insert into offerRide(source,destination,date,time,av_seat,amount) values('"+from+"','"+to+"','"+date+"','"+time+"','"+seats+"','"+amount+"')");
            JOptionPane.showMessageDialog(null,"Ride Published");
            jPanel6.setVisible(false);
            jPanel8.setVisible(true);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String from = booking_from.getText();
        String to = booking_to.getText();
        String date = booking_date.getText();
        String time = booking_time.getText();
        String seats = booking_passenger.getText();
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carpooling","root","root");

            // Create SQL query
            String sql = "SELECT * from offerride where "
                    + "source='"+from+"' and destination='"+to+"' and date='"+date+"' and time='"+time+"' "
                    + "and av_seat>='"+seats+"'";

            // Create Statement and execute query
            Statement statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery(sql);

            // Append data to StringBuilder
            StringBuilder sb = new StringBuilder();
            while (resultSet.next()) {
                String id = resultSet.getString("id");
                String from1 = resultSet.getString("source");
                String to1 = resultSet.getString("destination");
                String date1 = resultSet.getString("date");
                String time1 = resultSet.getString("time");
                String seats1 = resultSet.getString("av_seat");
                String amount1 = resultSet.getString("amount");
                sb.append("Id: ").append(id).append(", Source: ").append(from1).append(", Destination: ").append(to1).append(", Date: ").append(date1)
                        .append(", Time: ").append(time1).append(", Available Seats: ").append(seats1).append(", Amount: ").append(amount1).append("\n");
            }

            // Set data to JTextArea
            details.setText(sb.toString());

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog("Enter the id of the ride you want to book");

        String seats = booking_passenger.getText();
        Connection con = null;
        PreparedStatement selectStmt = null;
        PreparedStatement updateStmt = null;
        ResultSet resultSet = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carpooling", "root", "root");

            // Convert id and seats to integer
            int id = Integer.parseInt(str);
            int newSeats = Integer.parseInt(seats);

            // Create and execute SELECT query to fetch the current available seats
            String selectSQL = "SELECT av_seat FROM offerride WHERE id = ?";
            selectStmt = con.prepareStatement(selectSQL);
            selectStmt.setInt(1, id);
            resultSet = selectStmt.executeQuery();

            if (resultSet.next()) {
                int initialSeats = resultSet.getInt("av_seat");

                if (initialSeats >= newSeats) {
                    int updatedSeats = initialSeats - newSeats;

                    // Create and execute UPDATE query to update the available seats
                    String updateSQL = "UPDATE offerride SET av_seat = ? WHERE id = ?";
                    updateStmt = con.prepareStatement(updateSQL);
                    updateStmt.setInt(1, updatedSeats);
                    updateStmt.setInt(2, id);
                    int rowsUpdated = updateStmt.executeUpdate();

                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(null, "Booking done");
                        if(updatedSeats == 0){
                            String deleteSQL = "delete from Offerride where id = ?";
                            PreparedStatement deleteStmt = con.prepareStatement(deleteSQL);
                            deleteStmt.setInt(1, id);
                            deleteStmt.executeUpdate();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Booking failed. Please try again.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Not enough available seats.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ride not found.");
            }

            jPanel8.setVisible(false);
            jPanel1.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_bookActionPerformed

    private void bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bookMouseClicked

    private void offer_seatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offer_seatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offer_seatsActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        
        jPanel6.setVisible(false);
        jPanel8.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiftLoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiftLoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiftLoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiftLoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiftLoop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField L_Password;
    private javax.swing.JCheckBox L_ShowPassword;
    private javax.swing.JTextField L_Username;
    private javax.swing.JButton S_Back;
    private javax.swing.JRadioButton S_Female;
    private javax.swing.JLabel S_FillPassword;
    private javax.swing.JTextField S_Name;
    private javax.swing.JPasswordField S_Password;
    private javax.swing.JPasswordField S_RetypePassword;
    private javax.swing.JTextField S_SecAns;
    private javax.swing.JComboBox<String> S_SecQues;
    private javax.swing.JButton S_Submit;
    private javax.swing.JTextField S_Username;
    private javax.swing.JRadioButton S_male;
    private javax.swing.JButton adminButton;
    private javax.swing.JLabel adminIcon;
    private javax.swing.JButton book;
    private javax.swing.JTextField booking_date;
    private javax.swing.JTextField booking_from;
    private javax.swing.JTextField booking_passenger;
    private javax.swing.JTextField booking_time;
    private javax.swing.JTextField booking_to;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea details;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JLabel homeImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField offer_amount;
    private javax.swing.JTextField offer_date;
    private javax.swing.JTextField offer_from;
    private javax.swing.JTextField offer_seats;
    private javax.swing.JTextField offer_time;
    private javax.swing.JTextField offer_to;
    private javax.swing.JLabel seak_date;
    private javax.swing.JLabel seak_from;
    private javax.swing.JLabel seak_pass;
    private javax.swing.JLabel seak_time;
    private javax.swing.JLabel seak_to;
    private javax.swing.JLabel signUp;
    // End of variables declaration//GEN-END:variables
    class library extends SwingWorker{

        @Override
        protected Object doInBackground() throws Exception {
            int i = 1;
            while(true){
                try{
                    BufferedImage bi = ImageIO.read(new File("E:\\GitsteinPrograms\\library management system project\\carpool"+i+".jpg"));
                    Image ii = bi.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT);
                    jLabel1.setIcon(new ImageIcon(ii));
                    Thread.sleep(2000);
                    i++;
                    if(i == 4){
                        i = 1;
                    }
                }
                catch(Exception e){
                    System.out.println(e);
                }
            }
        }
    }
    class home extends SwingWorker{

        @Override
        protected Object doInBackground() throws Exception {
            try{
                    BufferedImage bi = ImageIO.read(new File("E:\\GitsteinPrograms\\library management system project\\carpool3.jpg"));
                    Image ii = bi.getScaledInstance(homeImage.getWidth(), homeImage.getHeight(), Image.SCALE_DEFAULT);
                    homeImage.setIcon(new ImageIcon(ii));
                    
            }
            catch(Exception e){
                    System.out.println(e);
            }
            return 1;
        }
    }
}
